### ISSUE TITLE
Dataset Not Available

### ISSUE THREAD

**Issue by tdsuper** [facebookresearch/co3d#1]
Hi, the dataset seems to be only available for the staffs of Facebook AI Research. Could the dataset be released for other people?

**Comment by shapovalov** [comment]
@tdsuper Thanks for your interest! You should be able to download the dataset from https://ai.facebook.com/datasets/co3d-downloads/ .
Can you please try and confirm if it works for you?

**Comment by tdsuper** [comment]
@shapovalov The dataset can be downloaded from the link. Thanks very much!

**Comment by tdsuper** [comment]
@shapovalov Hi, could you please provide the category name for each part of the dataset? If there are category names, we can download the parts that we are interested.
