### ISSUE TITLE
3D bounding boxes from point clouds

### ISSUE THREAD

**Issue by mikkelmedm** [facebookresearch/co3d#14]
Helloo 

Thanks for creating this awesome dataset :) 

Im trying to make 3D bounding boxes from the point clouds using pytorch3D [Pointclouds.get_bounding_boxes](https://github.com/facebookresearch/pytorch3d/blob/4281df19cefb640067a49b961587342d9e4d85ba/pytorch3d/structures/pointclouds.py#L937) method, however my results as of now looks completely off - code for transforming object point clouds to 3D bounding boxes:

```
def bb_vertex_from_sizes(sizes, cloud_idx=0):
    sizes = sizes[cloud_idx]
    x_min, x_max = sizes[0]
    y_min, y_max = sizes[1]
    z_min, z_max = sizes[2]

    point_0 = [x_min, y_min, z_min]
    point_1 = [x_min, y_min, z_max]
    point_2 = [x_min, y_max, z_min]
    point_3 = [x_min, y_max, z_max]
    point_4 = [x_max, y_min, z_min]
    point_5 = [x_max, y_min, z_max]
    point_6 = [x_max, y_max, z_min]
    point_7 = [x_max, y_max, z_max]

    return torch.Tensor(np.stack([point_0, point_1, point_2, point_3, point_4, point_5, point_6, point_7]))


dataset = dataset_zoo("co3d_multisequence", "data", "cup", load_point_clouds=True, test_on_train=False)
train_ds = dataset["train"]
n = random.randint(0, 10000)
frame = train_ds[n]
image = frame.image_rgb.permute(1,2,0).numpy()
point_cloud = frame.sequence_point_cloud[0]
bbox = bb_vertex_from_sizes(point_cloud.get_bounding_boxes())
bbox_proj = frame.camera.transform_points_screen(bbox, image_size=image.shape[:2])
bbox_proj = bbox_proj.int().numpy()[:,:2]


fig, ax = plt.subplots(figsize=(15,10))
ax.imshow(image)
ax.scatter(bbox_proj[:, 0], bbox_proj[:, 1])
```

![output_bbox](https://user-images.githubusercontent.com/38498170/137292970-5472073a-1286-4b39-ba2f-80777004f5c9.png)
![output_pcl](https://user-images.githubusercontent.com/38498170/137292975-279688b7-41df-4a1e-8a0c-7092040cd80c.png)

Just wanted to check in, if this at all would be possible before diving deeper into it. 

The calculated 3D vertices does not seem to be correct, even when the point clouds seem to be without too many outliers.
I see that the point clouds sometimes have outliers, so my approach would be to somehow filter out these by perhaps only accounting for the points inside of the 2d bounding box of the object, however not sure if this is the best approach, though this wouldnt fix the bounding boxes for my current implementation.

Hope you can help :)

**Comment by davnov134** [comment]
Yes, the objects are not semantically aligned. This is an additional challenge when moving away from synthetic datasets. Check out our paper for models that approach the issue by being invariant to the global transforms of the coordinate frames.
