### ISSUE TITLE
The near and far bounds of camera

### ISSUE THREAD

**Issue by w2kun** [facebookresearch/co3d#18]
Thanks for releasing the dataset! I plan to train a nerf model using the implementation in Pytorch3D on CO3D but have problem on choosing the near and far bounds of camera. Can you provide some advices on how to calculate the two values or give a experimental reference?

**Comment by w2kun** [comment]
Thanks for the reply!

**Comment by w2kun** [comment]
> 
> 
> Hi, we usually set adaptive near/far bounds:
> 
>     * All objects are roughly centered around 0,0,0 and fit into a 3D sphere with a diameter of `8`.
> 
>     * Hence, we set:
> 
> 
> ```
> near = camera_center.norm(dim=-1) - 8
> far = camera_center.norm(dim=-1) + 8
> ```

Sorry to bother you, but I want to make sure I get the point. If I want to sample points along a ray, is it right to set min_depth and max_depth to 0.0 and 16.0?

**Comment by davnov134** [comment]
No, I mean exactly what is being said above :) . I. e. that near and far has to be set based on the camera_center. If your camera center lies far from (0,0,0), the near plane has to be adjusted accordingly, i.e. increased to move it closer to the center of the scene.

**Comment by w2kun** [comment]
Get it! I have another question about sphere size you mentioned above. According to the formula, the sphere seems to have a radius (instead of diameter) of 8. Can you clarify this?

**Comment by davnov134** [comment]
Yes, radius of 8, thanks for spotting this.

**Comment by w2kun** [comment]
It's my pleasure. And thanks again for your timely reply, it indeed helps me.
