### ISSUE TITLE
tools.vis_utils not included? 

### ISSUE THREAD

**Issue by shadowninjazx** [facebookresearch/co3d#19]
I am trying to run eval_demo.py with visualizations. In evaluation/evaluate_new_view_synthesis.py on line 203:
`imports from tools.vis_utils import make_depth_image`
it imports from tools.vis_utils. However, I cannot find the corresponding file in the tools folder. Is this something that is not released yet?

**Comment by davnov134** [comment]
Hi, sorry for the glitch, the function has now been added.

**Comment by shadowninjazx** [comment]
Thank you!
