### ISSUE TITLE
Automating download for remote machines

### ISSUE THREAD

**Issue by shubham-goel** [facebookresearch/co3d#2]
Hi, thanks for the dataset!!

I can download it on my local machine by clicking on the links at https://ai.facebook.com/datasets/co3d-downloads/. But this is a bit tedious for remote machines.

Is there a recommended way for automating the download for the entire dataset onto a remote machine? 

Thanks in advance!

**Comment by OasisYang** [comment]
Same question. @shubham-goel If you have a solution, would you like to share it. Thanks in advance!

**Comment by davnov134** [comment]
Hi, thanks for your interest in our dataset!

We anticipated this as a possible issue and, very soon, we will also allow users to download a list of links that would be plugged into a download script. 

We will keep you posted.

**Comment by shubham-goel** [comment]
@OasisYang my current solution is to start the download on my laptop browser, copying the download link from the browser's download page, and `wget`-ing it on a remote machine. 

The most cumbersome part of this process -- copying the links from the browser's download page, could be automated for chrome using [this script](https://superuser.com/questions/1112327/how-can-i-export-all-downloads-links-from-chrome-downloads).

**Comment by eldar** [comment]
Hi, the dataset looks cool! Hijacking the issue here. It would also be very useful to provide a description of which category each of the 50 zip archives corresponds to: for those users who do not want to download the entire dataset and are interested only in select categories. (For instance, I need just the car category).

**Comment by davnov134** [comment]
Thanks @eldar. We are indeed also working on the solution. Both issues (enabling bulk-download on headless machines, category-named links) should be fixed by the end of next week (Aug 13th).

**Comment by eldar** [comment]
Thanks @davnov134!

**Comment by davnov134** [comment]
Hi, the batch download has now been made available. Please see the readme for more info.

**Comment by DeriZSY** [comment]
The download script failed. Seems like the targets for download are too small for chunk size 1024.

![Screen Shot 2021-08-16 at 3 32 11 PM](https://user-images.githubusercontent.com/25219214/129527437-63c42fd6-c3b4-4af1-bef4-82da0bb69c62.png)

**Comment by DeriZSY** [comment]
The downloaded files after the above problem fixed
![Screen Shot 2021-08-16 at 3 33 40 PM](https://user-images.githubusercontent.com/25219214/129527546-fc446c64-b9f9-4b2f-a69c-62092c50f418.png)
@davnov134

**Comment by davnov134** [comment]
Hi @DeriZSY, are you still having the issue? I tried the download script on both mac and a ubuntu linux and it worked in both cases.

**Comment by DeriZSY** [comment]
> Hi @DeriZSY, are you still having the issue? I tried the download script on both mac and a ubuntu linux and it worked in both cases.

yeah, it's working now!
