### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by w2kun** [facebookresearch/co3d#26]
Hi,

Thanks for releasing the dataset. I encountered some problems when trying to download the dataset.

I encountered a timeout error when downloading the couch data from the  CO3D downloads page. I tried to download it again, but found that it became 647MB in size and broke. The timeout error are also raised when I tried to download data of some other categories. I turned to use the `download_dataset.py` script but still encountered the timeout error.

Can you help me with this? Thanks very much.

**Comment by walsvid** [comment]
Same issue here, it seems that the CDN address has expired.
