### ISSUE TITLE
NerFormer 

### ISSUE THREAD

**Issue by AndyTang15** [facebookresearch/co3d#27]
Hello, many thanks for this impressive work!
Do you have any plans to share the code on NerFormer ?

**Comment by davnov134** [comment]
Hi yes, we are planning to release the code by the end of January.

**Comment by AndyTang15** [comment]
Many thanks for your reply. Looking forward to it!

**Comment by pwais** [comment]
will there be codes?

**Comment by pwais** [comment]
@davnov134 perhaps you mean Implicitron?  https://github.com/facebookresearch/pytorch3d/pull/1133

**Comment by shapovalov** [comment]
@pwais Yes, the reference implementation is released in Implicitron, you can use `repro_multiseq_nerformer.yaml` config to reproduce the results.
We are still working on Implicitron’s API; we plan to release the weights once the API is stable (we aim for June-July).
