### ISSUE TITLE
md5sum of dataset

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/co3d#29]
Hi,

Thanks for your great work and convenient script for downloading the dataset.

Would you have a plan to provide the md5sum for each zip file?

**Comment by davnov134** [comment]
Yes, we will provide the sums. For now you can use the ones kindly provided by @yxlao in https://github.com/facebookresearch/co3d/issues/12.

**Comment by ShoufaChen** [comment]
Thanks.
