### ISSUE TITLE
Technical report and baseline implementation.

### ISSUE THREAD

**Issue by wutong16** [facebookresearch/co3d#3]
Hi! Thanks for your wonderful dataset!!

I watched the video on YouTube for an overview of the dataset and the experiments, so would the technical report with those baseline results be available on arXiv? (Not sure if I missed it...) 
And do you plan to release the code for the baseline implementations mentioned in your video, especially the one for your CVPR paper?

Thanks!

**Comment by davnov134** [comment]
Hi, many thanks for your interest in our work.
We plan to release the tech report during this summer.
We will announce the release on social media.

**Comment by wutong16** [comment]
Thanks for your reply. Looking forward to your paper!
