### ISSUE TITLE
Dataset zip files on webpage are incomplete

### ISSUE THREAD

**Issue by jasonyzhang** [facebookresearch/co3d#30]
Hi,

Most of the zip files on the download page (https://ai.facebook.com/datasets/co3d-downloads/) are not the full archive and thus cannot be opened.

I have tried downloading using the `download_dataset.py` script and manually from the website.

Some of the links give HTTP 400 errors and do not download at all ( eg. broccoli, toytruck, microwave).
Most of the links download an incomplete file that does not match the checksums from #12. These files cannot be opened. For example, couch is a 648 MiB file that cannot be opened.
The categories that I was able to successfully download and decompress are donut, frisbee, plant, and tv.

Is it possible to double check the links on the website or host them on an alternative file sharing site?

Thanks in advance!

**Comment by davnov134** [comment]
Hello, sorry for the inconvenience, we are currently speaking to the team responsible for serving the files and will reply asap.

**Comment by jasonyzhang** [comment]
Thanks David!

**Comment by davnov134** [comment]
Hi, at last we managed to fix the hosting issue and updated the repository accordingly.
The file with links does not have to be downloaded anymore, instead the links are now static and included in the repository. To download the dataset, one simply needs to execute `python download_dataset.py --download_folder <DOWNLOAD_FOLDER>`. Please let me know in case of issues @jasonyzhang .
