### ISSUE TITLE
How to implement IDR on co3d dataset?

### ISSUE THREAD

**Issue by CoolChameleon** [facebookresearch/co3d#34]
Thanks for the wonderful work!
We are trying to replicate the work of IDR on your data set. However, we have a problem when using the preprocess_cameras.py provided by IDR to normalize the objects and let them fit in the standard sphere. If we try to run IDR model without normalizing, error occurs and we can't find any points during ray tracing. It seems the object often fall far from the origin. We wonder if you have got the same problem and how did you solve it?
Thanks a lot!

**Comment by davnov134** [comment]
Hi we have now released our implementation of all baselines on CO3D, IDR is a part of it:
https://github.com/facebookresearch/pytorch3d/tree/main/projects/implicitron_trainer
