### ISSUE TITLE
Problems with training original NeRF using CO3D dataset

### ISSUE THREAD

**Issue by chingweihsu0809** [facebookresearch/co3d#37]
Hello, thanks for the amazing work!

I failed to produce good result when using the CO3D dataset (single sequence) to train the original NeRF model. I'm wondering whether you've tried it and how's the result?

Thank you very much!

**Comment by davnov134** [comment]
Hi, we have now release reproduced baselines from the paper: https://github.com/facebookresearch/pytorch3d/tree/main/projects/implicitron_trainer
