### ISSUE TITLE
Which categories do you use in Table 3. of your paper?

### ISSUE THREAD

**Issue by CoolChameleon** [facebookresearch/co3d#43]
Hello!
I've read your paper and it says that you use 10 categories to test the category-centric new-view synthesis ability of your model. However, I didn't find out which 10 categories you used. So can you share their names please?
![Table 3](https://user-images.githubusercontent.com/23183849/163722949-a517bdf8-6182-4b3b-a52d-111272a4a14b.png)

**Comment by shapovalov** [comment]
Hi, thanks for this question.
We used the first 10/20 categories in [CO3D_CATEGORIES](https://github.com/facebookresearch/co3d/blob/d4895dd3976b1c6afb9e9221c047f67c678eaf08/dataset/dataset_zoo.py#L38) list for multi/single-sequence experiments, respectively. I.e. for multi-sequence (category-level training), we use "donut" through "plant". I hope it answers your question.

**Comment by CoolChameleon** [comment]
This is exactly what I am looking for! Thanks for the reply!
