### ISSUE TITLE
Bugs in foreground masks

### ISSUE THREAD

**Issue by yd-yin** [facebookresearch/co3d#46]
Hi, thanks for your great work on the big real-world dataset.

However, if you look at sequence `car/216_22790_47232` and other sequences, you will see that many of the foreground masks are wrongly annotated for background cars. Here, only 0038 and 0039 images are correct.
![cars](https://user-images.githubusercontent.com/37136395/168457967-39e92ca3-2229-4549-9d8b-d43a0550062b.png)

So the corresponding point cloud `car/216_22790_47232/pointcloud.ply` is incorrect, either.
![image](https://user-images.githubusercontent.com/37136395/168458016-4e07201f-2a84-4393-805e-5d82beee004c.png)

This happens in most of the sequences in `car`. Maybe the annotating algorithm masks several cars and you only retain one?

Will other categories be better?

**Comment by davnov134** [comment]
Indeed, all reconstructions are generated using an automated algorithm (as described in the paper).
We include the point_cloud_quality_score in SequenceAnnotations. Make sure to use point clouds with this score being high.

Note that we plan to release a new version very soon with better foreground masks/point clouds, stay tuned.

**Comment by davnov134** [comment]
Hello, please checkout the newly released version 2 of CO3D, it contains significantly improved segmentation masks.
