### ISSUE TITLE
get_eval_batches_map returns wrong shape of results

### ISSUE THREAD

**Issue by jkulhanek** [facebookresearch/co3d#55]
The get_eval_batches_map returns just a single image per evaluation sequence as opposed to the entire eval. sequence as described in the README. I believe the problem is here: https://github.com/facebookresearch/co3d/blob/77ecf83f8cd17d52a3fc38217fe32e14bfd84446/co3d/challenge/io.py#L317

**Comment by jkulhanek** [comment]
Also, a different shape is required for the mask as opposed to the documentation:
https://github.com/facebookresearch/co3d/blob/77ecf83f8cd17d52a3fc38217fe32e14bfd84446/co3d/challenge/co3d_submission.py#L306

**Comment by davnov134** [comment]
Hi, thanks a lot for spotting this. 
https://github.com/facebookresearch/co3d/commit/83ded49453f287f0a330e7fc4a1bd354878cb517 fixes the issue.
