### ISSUE TITLE
Pure black frames in single sequence dataset

### ISSUE THREAD

**Issue by leonidk** [facebookresearch/co3d#58]
Hi, 

I downloaded the single sequence teddybear data. It contains sequence number 598_91820_182418.

It looks like this contains several pure black frames (and hence pure black masks?). For example, frame000006.jpg to frame000010.jpg in that sequence. Is this expected/intentional? 

Thanks!

**Comment by davnov134** [comment]
Hi,

yes this is expected. These frames come from the official hidden test set of CO3D Challenge. They have been replaced with pure black frames while only the camera pose is correctly exposed to users.

Best,
David

**Comment by Bao-Long-Tran** [comment]
Hi, Thank for great work.
Regarding black frames, I would like to ask if is there any already script to filter out black frames (and its relevant ground truth)? Or users are expected to write script themselves?

Thanks,

**Comment by shapovalov** [comment]
@Bao-Long-Tran The challenge is not active any more. Unless you have a good reason, please use the recent version of the dataset: https://uco3d.github.io/
It won’t have any black frames.
