### ISSUE TITLE
(1) Where are camera parameters stored in the dataset? (2) About depth-pointcloud consistency.

### ISSUE THREAD

**Issue by YunzeMan** [facebookresearch/co3d#62]
I just started using this amazing dataset. However, looking at the unzipped directory systems, I'm not quite sure where the camera parameters (intrinsic and extrinsic matrices) are stored.

Are they stored in `frame_annotations.jgz` or some other places?

One additional question is about the correspondence between depth map and point cloud. If I convert one GT depth map into a point cloud with the GT camera matrix, will it be consistent with the GT point cloud `pointcloud.ply`? 

Thank you.

**Comment by davnov134** [comment]
Hi, camera annotations for each category are indeed in `frame_annotations.jgz`.
`pointcloud.ply` will be approximately consistent with unprojected depths, i.e. you will not be able to extract a precise correspondence between the point cloud points and the depth map points, but they will follow the same surface.

**Comment by YunzeMan** [comment]
Thanks. This is very helpful.
