### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by wbjang** [facebookresearch/co3d#65]
Hello, 

Thank you very much for this amazing and massive dataset.
I tried to download 'teddybear' of this CO3Dv2 dataset.
However, I encountered this 'Bad CRC-32' error, which I could not fix. Please see this attached screen shot. I used the provided code to download the category.

![Screenshot 2023-02-21 at 17 32 17](https://user-images.githubusercontent.com/32883157/220418027-51d223b1-8a55-4bad-ae06-d221b029f4e2.png)

I have deleted and tried to download again, but the same file causes the issue.

Cheers,
Wonbong

**Comment by wbjang** [comment]
I can download the 'car' category without any issue - I suspect this may be related to the file itself.

**Comment by wbjang** [comment]
Hello @davnov134,

Thank you for reaching out to me.

I retried to download the file, but unfortunately, I still encountered some issues. This time, a different file seems to be the problem. After investigating, it appears that the Python download script and my conda environment may be causing the issue.

While looking for a solution, I stumbled upon this link - https://ai.facebook.com/datasets/co3d-downloads/ - for the co3d dataset. However, it's not clear whether this is the same dataset that the Python script downloads. (as it does not explicitly mention that it is co3dv2 dataset)

Can you please confirm whether the dataset from the above link is the same as the one downloaded by the Python script?

Thank you!

Best regards,
Wonbong

**Comment by davnov134** [comment]
Hi, ok let me know if I can help with the env somehow.

https://ai.facebook.com/datasets/co3d-downloads/ corresponds to v1 and is deprecated, please only refer to the github repository for downloading v2.

**Comment by wbjang** [comment]
Hello @davnov134 , I found out that the issue was my harddisk. I can successfully download using another external drive using the provided script. Thank you!
