### ISSUE TITLE
Pytorch independent usage convention

### ISSUE THREAD

**Issue by Pauljanson002** [facebookresearch/co3d#67]
Hi, thanks for the wonderful work. I am trying to use the dataset with a custom data loader. For that, I need the transform matrix in the open cv/ open gl convention. I referred to the section  ["PyTorch-independent usage"](https://github.com/facebookresearch/co3d/tree/main#pytorch-independent-usage) and I am able to get the R, t,f, and other parameters. But I am confused about the convention used to represent these parameters in the root form.  

1. Could you please clearly state what the convention used here is? 
2. is the same convention used for v1 and v2 in the jgz files of each? ( I want to know what is the base convention used in the jgz files to store the parameters for v1 and v2) 

Thanks in advance

**Comment by davnov134** [comment]
Hi, the conventions are the same as in pytorch3d. If you are after the opencv convention, I strongly suggest the following function: https://github.com/facebookresearch/pytorch3d/blob/741777b5b5bdfb498173d3911bdf4978b49a12ec/pytorch3d/utils/camera_conversions.py#L65

It takes as input a PerspectiveCameras object containing camera parameters in pytorch3d convention (i.e. the parameters stored in the CO3D .jgz files) and outputs K,R,T in the opencv convention.

**Comment by Pauljanson002** [comment]
Thanks for the information.
