### ISSUE TITLE
Is it possible to download only one category?

### ISSUE THREAD

**Issue by YJ-142150** [facebookresearch/co3d#68]
Thanks for great work.
As I use a personal desktop, it's hard to download the entire dataset, the entire dataset of a particular category.
Is there any other way to download part of a category maintaining dataset format?

**Comment by davnov134** [comment]
Hi, the first part file of each category contains the necessary metadata, the remaining parts contain category sequences. You can download just the first part and an arbitrary number of the subparts. You can then postprocess the metadata to only contain the sequences which you have downloaded and later use all the tooling we provide without issues.

**Comment by YJ-142150** [comment]
Thank you for answering the question!
