### ISSUE TITLE
Camera Position Plots Don't Seem to Match Expected Circular Motion

### ISSUE THREAD

**Issue by jaymefosa** [facebookresearch/co3d#69]
I've been working on visualizing the camera positions and directions using the camera annotations (the rotation matrix R and translation vector T) from a dataset. I put together some 2D subplots for the XY, XZ, and YZ planes to get a better idea of the camera motion. However, the plots aren't really showing the circular camera motion that I was expecting.

When I take a look at the actual images, the camera movement seems to follow a circular or oval path. But, the plots I made using the camera annotations don't seem to match up with that. I'm not entirely sure if I'm interpreting the camera annotations correctly or if there's something I'm missing.

Could you help me out with understanding the camera coordinate system used in the annotations or give me some tips on how to properly visualize the camera positions and directions using the data provided?

Thanks a bunch!

![Screenshot from 2023-03-19 16-19-05](https://user-images.githubusercontent.com/92468/226216076-7a3ed570-3b22-4c8d-abad-f01607aadf93.png)

**Comment by davnov134** [comment]
Hi, `viewpoint.T` is not the location of the camera center, but rather the translation vector in the camera coordinate frame.
In order to obtain the camera center, you need to convert it as follows:
`camera_center = -np.array(viewpoint.R) @ np.array(viewpoint.T)`

Extract such camera centers for all cameras in the scene and you will see a nice circle.

**Comment by jaymefosa** [comment]
Thank you very much! I was able to get the render of the apple :)

![Screenshot from 2023-03-21 14-55-17](https://user-images.githubusercontent.com/92468/226750494-2a8d80da-4d63-4d0c-b448-2bc28b3911b0.png)
