### ISSUE TITLE
Camera Intrinsic parameter

### ISSUE THREAD

**Issue by TropicalPenguinn** [facebookresearch/co3d#74]
Can you tell me the intrinsic parameter of camera that you have used to make the dataset?

**Comment by davnov134** [comment]
Hi, each frame is annotated with a specific set of intrinsics. You can find this information in the frame_annotations.jgz files bundled in the dataset.

**Comment by shapovalov** [comment]
See also the relevant part of the example if you use JsonIndexDataset for high-level access to the metadata: https://github.com/facebookresearch/co3d/blob/main/examples/show_co3d_dataset.py#L147

`data_to_show_collated.camera` is an instance of `PerspectiveCameras`, where you can access `focal_length` and `principal_point` attributes.

Also to note that the intrinsics were estimated during SfM.

I will close the thread but feel free to reopen for further clarifications.
