### ISSUE TITLE
Format of camera poses listed in frame_annotations.jgz

### ISSUE THREAD

**Issue by justachetan** [facebookresearch/co3d#84]
Hi! Are the camera poses (rotation and translation vector) listed in `frame_annotations.jgz` file in each category sub-folder in the world-to-camera format or the camera-to-world format?

Any help on this would be much appreciated!

**Comment by shapovalov** [comment]
The cameras are in Pytorch3D format, and if you use the provided data loaders, they will be loaded correctly.
In case you use different frameworks, it should be: `x_cam = x_world @ R + T` (and then decalibrate with intrinsics if needed).
More info: https://pytorch3d.org/docs/cameras
